### ISSUE TITLE
Detailed description of prof 1

### ISSUE THREAD

**Issue by Niblett** [MTM6330-F18/Final---Rebeccapurple#16]

**Comment by benaldrich** [comment]
"I have been teaching for 5 years at Algonquin College.

I completed the IMM program at Algonquin College in 2009 (1-year program which was named Interactive Multimedia at the time). When I was a student of IMM, I didn't have a plan on teaching anywhere. When I started working as the front-end web developer producing interactive online courses, I became interested in teaching too. My other profession is Industrial Engineering (University of Ljubljana). 

I teach web development and programming trying to implement the hands-on experience as much as possible. Also, I try to create the informal classroom atmosphere for students to feel free to engage with questions, suggestions, comments or complaints. The course I teach delivers the fundamental skills in HTML and CSS that are necessary for learning front-end and back-end programming in the upcoming semesters.

Ideally, a student who completes the IMD program should be a junior web developer at the competitive level eager to keep learning through the work. Junior web developer should be able to use currently popular and competitive technologies to handle the projects based on graphics (static and motion), video, popular CMS-s, front-end and back end programming (in the scope of junior level). 

I hope this answers all of your questions.

Regards,
Amel"
